In [14]:
import keras_cv
import tensorflow as tf

In [30]:
# Class mapping
class_ids = [
    "10c",
    "10d",
    "10h",
    "10s",
    "2c",
    "2d",
    "2h",
    "2s",
    "3c",
    "3d",
    "3h",
    "3s",
    "4c",
    "4d",
    "4h",
    "4s",
    "5c",
    "5d",
    "5h",
    "5s",
    "6c",
    "6d",
    "6h",
    "6s",
    "7c",
    "7d",
    "7h",
    "7s",
    "8c",
    "8d",
    "8h",
    "8s",
    "9c",
    "9d",
    "9h",
    "9s",
    "Ac",
    "Ad",
    "Ah",
    "As",
    "Jc",
    "Jd",
    "Jh",
    "Js",
    "Kc",
    "Kd",
    "Kh",
    "Ks",
    "Qc",
    "Qd",
    "Qh",
    "Qs",
]
class_mapping = dict(zip(range(len(class_ids)), class_ids))


def create_custom_model():
    backbone = keras_cv.models.YOLOV8Backbone.from_preset("yolo_v8_xl_backbone_coco")
    yolo = keras_cv.models.YOLOV8Detector(
        num_classes=len(class_mapping),
        bounding_box_format="center_xywh",
        backbone=backbone,
        fpn_depth=1,
    )
    return yolo


def load_model():
    reconstructed_yolo = create_custom_model()
    reconstructed_yolo.load_weights("/Users/sergi/code/seeergiii/blackjack/blackjack/computer_vision/models__20230905-0551_model_weights.h5")
    return reconstructed_yolo


def prediction(image, model):
    input_image = tf.image.resize(image, (416, 416))
    input_image = tf.expand_dims(input_image, axis=0)
    y_pred = model.predict(input_image)
    return y_pred


In [31]:
model = load_model()

In [32]:
import cv2

In [52]:
img = cv2.imread("test.jpg", cv2.COLOR_RGB2BGR)

tf.io_decode_image()

cv2input_image = tf.convert_to_tensor(img, dtype=tf.uint8)
cv2input_image

<tf.Tensor: shape=(416, 416, 3), dtype=uint8, numpy=
array([[[ 76,  65,  57],
        [ 78,  67,  59],
        [ 81,  69,  65],
        ...,
        [187, 183, 182],
        [176, 172, 171],
        [168, 164, 163]],

       [[ 78,  67,  59],
        [ 81,  70,  62],
        [ 84,  72,  68],
        ...,
        [194, 190, 189],
        [188, 184, 183],
        [183, 179, 178]],

       [[ 74,  63,  55],
        [ 78,  67,  59],
        [ 81,  69,  65],
        ...,
        [198, 194, 193],
        [197, 193, 192],
        [197, 193, 192]],

       ...,

       [[ 55,  52,  61],
        [ 53,  52,  61],
        [ 54,  53,  62],
        ...,
        [106, 101, 102],
        [108, 105, 107],
        [113, 112, 114]],

       [[ 57,  54,  56],
        [ 55,  54,  56],
        [ 56,  55,  57],
        ...,
        [102,  97,  98],
        [105, 102, 104],
        [111, 108, 110]],

       [[ 42,  40,  40],
        [ 44,  42,  42],
        [ 46,  44,  44],
        ...,
        [100,  95,  9

In [48]:
image = tf.io.read_file("test.jpg")
image = tf.image.decode_jpeg(image, channels=3)
image

<tf.Tensor: shape=(416, 416, 3), dtype=uint8, numpy=
array([[[ 56,  66,  75],
        [ 58,  68,  77],
        [ 63,  70,  80],
        ...,
        [179, 183, 186],
        [169, 173, 176],
        [160, 164, 167]],

       [[ 58,  68,  77],
        [ 62,  71,  80],
        [ 66,  73,  83],
        ...,
        [186, 190, 193],
        [180, 184, 187],
        [175, 179, 182]],

       [[ 55,  64,  73],
        [ 58,  67,  76],
        [ 63,  70,  80],
        ...,
        [190, 194, 197],
        [190, 194, 197],
        [189, 193, 196]],

       ...,

       [[ 61,  52,  53],
        [ 61,  52,  53],
        [ 62,  53,  54],
        ...,
        [101, 102, 104],
        [105, 105, 107],
        [112, 112, 112]],

       [[ 55,  53,  54],
        [ 56,  54,  55],
        [ 57,  55,  56],
        ...,
        [ 97,  97,  99],
        [104, 102, 105],
        [109, 107, 108]],

       [[ 40,  40,  42],
        [ 42,  42,  44],
        [ 43,  44,  46],
        ...,
        [ 96,  96,  9

In [ ]:
image = tf.cast(image, tf.float32)
image = tf.image.resize(image, (416, 416))
image = tf.expand_dims(image, axis=0)

In [46]:
y_pred = model.predict(image)

1/1 [==============================] - 1s 578ms/step


In [47]:
y_pred

{'boxes': array([[[181.70502 , 237.56865 ,  22.59613 ,  42.62137 ],
         [244.99913 , 223.96404 ,  28.643219,  40.44754 ],
         [ 57.59047 , 108.34386 ,  23.818619,  43.961212],
         [269.0453  , 207.85745 ,  31.383438,  36.496155],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  -1.      ],
         [ -1.      ,  -1.      ,  -1.      ,  